services:
  node-app:
    image: shalintim/node-app:latest
    container_name: node-app-container
    expose:
      - "3000"
    restart: always
    networks:
      - node-network

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    depends_on:
      - node-app
    restart: always
    networks:
      - node-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    networks:
      - node-network
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h;
      done"
volumes:
  certbot-www:
  certbot-conf:
networks:
  node-network:
    driver: bridge
