worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    

    # --------------------------------
    # Upstream (Node.js containers)
    # --------------------------------
    upstream nodejs_cluster {
        least_conn;
        server node-app:3000;
    }

    # --------------------------------
    # HTTP (Port 80) - Challenge + Redirect
    # --------------------------------
    server {
        listen 80;
        server_name app.shalintimalsina.com.np www.app.shalintimalsina.com.np;

        # Let's Encrypt HTTP-01 challenge
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirect everything else to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # --------------------------------
    # HTTPS (Port 443) - SSL + Proxy
    # --------------------------------
   server {
    listen 443 ssl;
    server_name app.shalintimalsina.com.np www.app.shalintimalsina.com.np;

    ssl_certificate     /etc/letsencrypt/live/app.shalintimalsina.com.np/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.shalintimalsina.com.np/privkey.pem;

    location / {
        proxy_pass http://nodejs_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
}
