name: CI CD pipeline 


# This is the events that is going to trigger this whole workflow.
on: 
  push:
    branches: [ 'main']
  
jobs:

# Each jobs is going to run on a seperate machine

# This is just the identifier or the name of the job
  Compile: 
  #  This is where the Pipeline is going to run (Shared runner)
    runs-on: self-hosted 
    # Now the steps are defined inside
    steps:   
    # Codes are going to be pulled inside the runner
    - name: Checkout Repo in the runner  
    # Uses the pre-defined actions from the marketplace
      uses: actions/checkout@v6.0.2

    - name: Setup Nodejs 
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install Dependencies
      run: npm install 
         
    - name: Run the express server ,health check and stop the express server.
      run:  | 
         node server.js & SERVER_PID=$!
         sleep 5 
         curl http://localhost:3000/health
         kill $SERVER_PID

  
  Security: 
    
    needs: Compile
    runs-on: self-hosted

    steps:
      - name: Checkout the Code 
        uses: actions/checkout@v6.0.2

     
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Install Gitleaks (binary, fast)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 \
            -o gitleaks && chmod +x gitleaks && sudo mv gitleaks /usr/local/bin

      - name: Run Gitleaks scan
        run: |
          gitleaks detect \
            --source . \
            --report-path gitleaks-report.json \
            --report-format json


