name: CI CD pipeline 


# This is the events that is going to trigger this whole workflow.
on: 
  push:
    branches: [ 'main']
  
jobs:

# Each jobs is going to run on a seperate machine

  job-1: # This is just the identifier or the name of the job
    runs-on: ubuntu-latest #  This is where the Pipeline is going to run (Shared runner)
    steps:  # Now the steps are defined inside 
    - name: Checkout Repo in the runner  # Codes are going to be pulled inside the runner
      uses: actions/checkout@v6.0.2 # Us es the pre-defined actions from the marketplace

    - name: Setup Nodejs 
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install Dependencies
      run: npm install 
         
    - name: Run the express server 
      run:  | 
         node server.js 
         sleep 5 
    - name : Check the health status
      run: curl http://localhost:3000/health

  # job-2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name:      


      