name: CI CD pipeline 


# This is the events that is going to trigger this whole workflow.
on: 
  push:
    branches: [ 'main']
  
jobs:

# Each jobs is going to run on a seperate machine

# This is just the identifier or the name of the job
  job-1: 
  #  This is where the Pipeline is going to run (Shared runner)
    runs-on: ubuntu-latest 
    # Now the steps are defined inside
    steps:   
    # Codes are going to be pulled inside the runner
    - name: Checkout Repo in the runner  
    # Uses the pre-defined actions from the marketplace
      uses: actions/checkout@v4 

    - name: Setup Nodejs 
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install Dependencies
      run: npm install 
         
    - name: Run the express server ,health check and stop the express server.
      run:  | 
         node server.js & SERVER_PID=$!
         sleep 5 
         curl http://localhost:3000/health
         kill $SERVER_PID


  # job-2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name:      


      